services:
  backend:
    image: node:latest
    container_name: food-explorer-backend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3333:3333"
      - "5555:5555"
    # use your own DATABASE_URL
    environment:
      DATABASE_URL: postgres://user:password@db:5432/food-explorer-db
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: food-explorer-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food-explorer-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
